apps/posts/urls.py
"""Posts URLs."""
# Django
from django.urls import path

# Views
from apps.posts import views

urlpatterns = [
    path('', views.PostsFeedViews.as_view(), name="home"),
    path('posts/new', views.CreatePostView.as_view(), name="create_post"),
    path('posts/<int:pk>', views.PostDetailView.as_view(), name="detail_post"),
]

apps/users/urls.py
"""Posts URLs."""
# Django
from django.urls import path

# Views
from apps.users import views

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('me/profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('me/profile/picture', views.UpdatePictureView.as_view(), name='update_picture'),
    path('<str:username>/', views.UserDetailView.as_view(), name='detail'),
]

jotagram/urls.py
# Django
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('hello/', local_views.hello),
    # path('sorted/', local_views.sorted_integers),
    # path('hi/<str:name>/<int:age>', local_views.say_hi),

    path('', include(('apps.posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jotagram | {% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <!-- My Style -->
    <style>
        body {
            background-color: #fbfbfb;
            overflow-x: hidden;
        }
        
        #navbar {
            background-color: #fff;
            height: 50px;
            -webkit-box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.5);
            -moz-box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.5);
            box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.5);
        }
        
        .padding5550 {
            padding: 5px 5px 0px 5px;
        }
        
        .nav-title-mobile {
            display: none;
        }
        
        .avatarRedondo-container {
            width: 50px;
            height: 50px;
        }
        
        .avatarRedondo {
            /* Aquí establecemos el tamaño del avatar, puedes poner los valores que quieras */
            height: 50px;
            width: 50px;
            /* Éstos valores no los tienes que cambiar ya que son en base a proporción */
            background-repeat: no-repeat;
            /*Para que la imagen no se repita */
            background-position: 50%;
            /*Centrar la imagen en el contenedor*/
            border-radius: 50%;
            /*Hace el efecto de redondear el contenedor*/
            background-size: cover;
            /*Hace que la imagen ocupe todo el contenedor*/
        }
        
        .avatarRedondo-nav {
            height: 23px!important;
            width: 23px!important;
        }
        
        .avatarRedondo-post {
            height: 35px!important;
            width: 35px!important;
            margin-right: 15px;
        }
        
        .avatarRedondo-detail {
            height: 150px!important;
            width: 150px!important;
        }
        
        .card-header {
            padding: 10px 0px 0px 0px;
        }
        /* Media queries */
        
        .input-file {
            padding-bottom: 32px;
        }
        
        .post-container {
            background-color: #fff;
            border: 1px solid #d9d9d9;
            padding: 15px 0px;
        }
        
        @media (max-width: 991px) {
            .nav-title-mobile {
                display: inline-block;
                padding-left: 5px;
            }
            nav {
                height: auto;
            }
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" id="navbar">
        <div class="container">
            <a href="{% url 'posts:home' %}">
                <img src="{% static 'img/logo.png' %}" alt="Okamigram" height="20px">
                <h5 class="nav-title-mobile">Jotagram</h5>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav" style="padding-left:20px;">
                <ul class="navbar-nav text-black ml-auto">
                    <li class="nav-item padding5550">
                        {% if request.user %}
                        <a href="{% url 'users:detail' request.user.username %}" data-toggle="tooltip" data-placement="bottom" title="Perfil">
                            <div class="avatarRedondo avatarRedondo-nav " style="background-image:url('{{ request.user.profile.picture.url }}')"></div>
                            <span class="nav-title-mobile">Perfil</span>
                        </a>
                        {% endif %}
                    </li>
                    <li class="nav-item padding5550">
                        <a href="{% url 'posts:home' %}" data-toggle="tooltip" data-placement="bottom" title="Home">
                            <i class="fa fa-home" style="font-size: 22px"></i>
                            <span class="nav-title-mobile">Home</span>
                        </a>
                    </li>
                    <li class="nav-item padding5550">
                        <a href="{% url 'posts:create_post' %}" data-toggle="tooltip" data-placement="bottom" title="Add Post">
                            <i class="fa fa-plus" style="font-size: 22px"></i>
                            <span class="nav-title-mobile">Add Post</span>
                        </a>
                    </li>
                    <li class="nav-item padding5550">
                        <a href="{% url 'users:logout' %}" data-toggle="tooltip" data-placement="bottom" title="Logout">
                            <i class="fa fa-sign-out-alt" style="font-size: 22px"></i>
                            <span class="nav-title-mobile">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mb-5">
        {% block content %}{% endblock %}
    </div>

    <!-- Import Javascript -->
    <script src="{% static 'jquery/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'popper/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'font-awesome/js/all.min.js' %}"></script>

    {% block script %}{% endblock %}

    <!-- My Script -->
    <!-- Initialize Tooltips -->
    <script>
        $(function() {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>

</html>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                    Previous
                </a>
        </li>
        {% endif %}
        <li class="page-item">
            <button class="page-link" disabled>
                    {{ page_obj.number }} or {{ page_obj.paginator.num_pages }}
                </button>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                    Next
                </a>
        </li>
        {% endif %}
    </ul>
</nav>