apps/posts/urls.py
"""Posts URLs."""
# Django
from django.urls import path

# Views
from apps.posts import views

urlpatterns = [
    path('', views.PostsFeedViews.as_view(), name="home"),
    path('posts/new', views.CreatePostView.as_view(), name="create_post"),
    path('posts/<int:pk>', views.PostDetailView.as_view(), name="detail_post"),
]

apps/users/urls.py
"""Posts URLs."""
# Django
from django.urls import path

# Views
from apps.users import views

urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('me/profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('me/profile/picture', views.UpdatePictureView.as_view(), name='update_picture'),
    path('<str:username>/', views.UserDetailView.as_view(), name='detail'),
]

jotagram/urls.py
# Django
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('hello/', local_views.hello),
    # path('sorted/', local_views.sorted_integers),
    # path('hi/<str:name>/<int:age>', local_views.say_hi),

    path('', include(('apps.posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
"""USers models."""
# Django
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    """Profile model."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(upload_to="users/pictures", blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

apps/users/forms.py
"""User forms."""
# Django
from django import forms

# Models 
from django.contrib.auth.models import User
from apps.users.models import Profile

class SignupForm(forms.Form):
    """Sign up form."""
    username = forms.CharField(min_length=4, max_length=50)
    
    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput())
    
    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        query = User.objects.filter(username=username).exists()

        if query:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data
    
    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data) # **data sirve para enviar todos los atributos del diccionario
        profile = Profile(user=user,picture="users/pictures/perfil.png")
        profile.save()

class PictureForm(forms.Form):
    """Pircture form."""
    picture = forms.ImageField(required=True)

apps/users/views.py
"""Users views."""
# Django
from django.urls import reverse, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from apps.posts.models import Post
from apps.users.models import Profile

# Forms
from apps.users.forms import PictureForm, SignupForm

class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = 'users/logged_out.html'

class SignupView(FormView):
    """Users sign up view."""
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username':username})
        
class UpdatePictureView(LoginRequiredMixin, UpdateView):
    """Update picture view."""
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username':username})

class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""
    template_name='users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username' # Este es el nombre del parametro en la ruta
    queryset = User.objects.all()
    context_object_name = 'user'
    login_url = '/users/login'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Okamigram - {% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">

    <!-- My Style -->
    <style>
        body {
            background: #fbfbfb;
            overflow-x: hidden;
        }
    </style>
</head>

<body>
    <div class="row justify-content-md-center d-flex align-items-center" id="row-content">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="text-center">
                        <!-- <img src="{% static 'img/logo150px.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 40%" alt=""> -->
                        <img src="{% static 'img/logo-ig.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 40%" alt="">
                    </div>
                    <!-- Content -->
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>


    <!-- Import Javascript -->
    <script src="{% static 'jquery/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'popper/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <!-- My Script -->
    <script>
        let content = document.getElementById('row-content')
        let height = window.innerHeight

        content.style.height = `${height}px`
    </script>
</body>

</html>

templates/users/base_session.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jotagram | {% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">

    <!-- My Style -->
    <style>
        body {
            background-color: #fbfbfb;
            overflow-x: hidden;
        }
    </style>
</head>

<body>
    <div class="row justify-content-md-center d-flex align-items-center" id="row-content">
        <div class="{% block col-tam %}{% endblock %}">
            <div class="card">
                <div class="card-body">
                    <div class="text-center">
                        <img src="{% static 'img/logo.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 100px" alt="">
                    </div>
                    <!-- Content -->
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>


    <!-- Import Javascript -->
    <script src="{% static 'jquery/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'popper/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <!-- My Script -->
    <script>
        let content = document.getElementById('row-content')
        let height = window.innerHeight

        content.style.height = `${height}px`
    </script>
</body>

</html>

templates/users/detail.html
<!-- Extending the base template -->
{% extends "base.html" %}
<!-- Title -->
{% block title %}@{{ user.username }} - Detail Profile{% endblock %}
<!-- Content -->
{% block content %}
<!-- <div class="row justify-content-md-center d-flex align-items-center" id="row-content"> -->
<div class="mt-5">
    <div class="row justify-content-md-center">
        <div class="col-sm-10">
            <div class="row">
                <div class="col-ms-4 d-flex justify-content-md-center">
                    <div class="avatarRedondo avatarRedondo-detail" style="background-image:url('{{ user.profile.picture.url }}')"></div>
                </div>
                <div class="col-sm-8" style="padding: 0px 50px">
                    <h2 style="font-weight: 100;">
                        {{ user.username}}
                        <!-- if user == request.user -->
                        {% if user == request.user %}
                        <a href="{% url 'users:update_profile' %}" class="ml-5 btn btn-sm btn-outline-info">
                            Edit profile
                        </a>
                        <!-- Else -->
                        {% else %}
                        <a href="" class="ml-5 btn btn-sm btn-outline-primary">Fallow</a>
                        <!-- EndIf -->
                        {% endif %}
                    </h2>
                    <div class="row mt-2" style="font-size: 1.2em">
                        <div class="col-sm-4">
                            <b>{{ user.profile.posts_count }}785</b> posts
                        </div>
                        <div class="col-sm-4">
                            <b>{{ user.profile.followers }}785</b> followers
                        </div>
                        <div class="col-sm-4">
                            <b>{{ user.profile.following }}785</b> following
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-sm-12 container text-center">
                            <p> {{ user.profile.biography }} </p>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                {% for post in posts%}
                <div class="col-sm-4 d-flex justify-content-center align-items-center" style="padding:5px">
                    <a href="{% url 'posts:detail_post' post.pk %}" class="border">
                        <img src="{{ post.photo.url}}" alt="{{ post.itle }}" class="img-fluid">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/login.html
<!-- Extending the base template -->
{% extends "users/base_session.html" %}
<!-- Title -->
{% block title %}Login{% endblock %}
<!-- Card-tam -->
{% block col-tam %} col-md-4 {% endblock %}
<!-- Content -->
{% block content %}
<div>
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter Username" value="{% if form.errors %}{{ form.username.value }}{% endif %}">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
        <div class="text-center mt-3">
            <a href="{% url 'users:signup' %}">Create an account</a>
        </div>

        {% if form.errors %}
        <div class="alert alert-danger mt-3 text-center" role="alert">
            Your username or password didn't match. Please try again.
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

templates/users/signup.html
<!-- Extending the base template -->
{% extends "users/base_session.html" %}
<!-- Title -->
{% block title %}Signup{% endblock %}
<!-- Card-tam -->
{% block col-tam %} col-md-6 {% endblock %}
<!-- Content -->
{% block content %}
<div>
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="username" name="username" placeholder="Enter Username" value="{% if form.errors %}{{ form.username.value }}{% endif %}" required>
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="email" name="email" placeholder="Enter Email Address" value="{% if form.errors %}{{ form.email.value }}{% endif %}" required>
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control {% if form.first_name.errors %}is-invalid{% endif %}" id="first_name" name="first_name" placeholder="Enter First Name" value="{% if form.errors %}{{ form.first_name.value }}{% endif %}" required>
                    <div class="invalid-feedback">
                        {% for error in form.first_name.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control {% if form.last_name.errors %}is-invalid{% endif %}" id="last_name" name="last_name" placeholder="Enter Last Name" value="{% if form.errors %}{{ form.last_name.value }}{% endif %}" required>
                    <div class="invalid-feedback">
                        {% for error in form.last_name.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" id="password" name="password" placeholder="Password" value="{% if form.errors %}{{ form.password.value }}{% endif %}" required>
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="password_confirmation">Password Confirmation</label>
                    <input type="password" class="form-control {% if form.password_confirmation.errors %}is-invalid{% endif %}" id="password_confirmation" name="password_confirmation" placeholder="Password Confirmation" value="{% if form.errors %}{{ form.password_confirmation.value }}{% endif %}"
                        required>
                    <div class="invalid-feedback">
                        {% for error in form.password_confirmation.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Register</button>
        </div>
        <div class="text-center mt-3">
            <a href="{% url 'users:login' %}">Do you already have an account? Log in</a>
        </div>

        {% if error %}
        <div class="alert alert-danger mt-3 text-center" role="alert">
            {{ error }}
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

templates/users/update_profile.html
<!-- Extending the base template -->
{% extends "base.html" %}
<!-- Title -->
{% block title %}@{{ request.user.username }} - Update Profile{% endblock %}
<!-- Content -->
{% block content %}
<div class="row justify-content-md-center d-flex align-items-center" id="row-content">
    <div class="col-md-5 mt-5">
        <div class="card">
            <div class="mt-3 text-center">
                <h5>Profile image</h5>
            </div>
            <div class="card-body">
                <form action="{% url 'users:update_picture' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="media">
                        <div class="avatarRedondo-container">
                            <div class="avatarRedondo" style="background-image:url('{{ profile.picture.url }}')"></div>
                        </div>
                        <div class="media-body">
                            <p class="ml-4 pt-2">
                                <input type="file" name="picture" id="picture" required>
                            </p>
                        </div>
                    </div>

                    {% for error in formPicture.picture.errors %}
                    <div class="alert alert-danger mt-3 text-center" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}

                    <div class="text-center">
                        <button type="submit" class="btn btn-primary btn-sm">Change image</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card mt-3">
            <div class="mt-3 text-center">
                <h5>Account info</h5>
            </div>
            <div class="card-body">
                <div class="text-center">
                    <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                </div>
                <form action="{% url 'users:update_profile' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input type="text" class="form-control {% if formProfile.website.errors %}is-invalid{% endif %}" id="website" name="website" placeholder="Enter Website" value="{% if formProfile.errors %}{{ formProfile.website.value }}{% else %}{{ profile.website }}{% endif %}">
                        <div class="invalid-feedback">
                            {% for error in formProfile.website.errors %} {{ error }} {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="biography">Biography</label>
                        <textarea class="form-control {% if formProfile.biography.errors %}is-invalid{% endif %}" id="biography" name="biography" rows="3">{% if formProfile.errors %}{{ formProfile.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                        <div class="invalid-feedback">
                            {% for error in formProfile.biography.errors %} {{ error }} {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">Phone Number</label>
                        <input type="text" class="form-control {% if formProfile.phone_number.errors %}is-invalid{% endif %}" id="phone_number" name="phone_number" placeholder="Phone Number" value="{% if formProfile.errors %}{{ formProfile.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}">
                        <div class="invalid-feedback">
                            {% for error in formProfile.phone_number.errors %} {{ error }} {% endfor %}
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary btn-sm">Update info</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}